"""Multi-page static dashboard, regenerated by every scan/refresh.

Pages (written to publish/ for GitHub Pages, plus copies at project root):
  index.html   — overview: KPIs, equity curve, positions with exit levels
  radar.html   — what the bot is looking at next: candidates vs threshold,
                 budget state, exit map, watchlist/avoid, learning progress
  history.html — closed-trade P/L, weekly performance, decision log

Every panel carries its own "as of" stamp because the underlying data ages
at different rates (prices vs research vs ledger).
"""
import datetime as dt
import json
import os

from bot import config, ledger, market, risk
from bot.config import ROOT

CSS = """
:root { --bg:#070A12; --panel:#0D1322; --panel2:#101829; --line:#1A2338;
  --ink:#EAF0FB; --mut:#8B99B5; --dim:#5C6B8C; --teal:#3EDDC5; --violet:#9F8CFF;
  --gain:#3DDC97; --loss:#FF7A70; --warn:#FFB454; }
* { margin:0; padding:0; box-sizing:border-box; }
html { -webkit-font-smoothing:antialiased; }
body { background:radial-gradient(1200px 500px at 70% -10%, #0D1730 0%, var(--bg) 55%);
  color:var(--ink); padding-bottom:64px; font-size:14px;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif; }
a { color:var(--teal); text-decoration:none; }
a:hover { text-decoration:underline; }
.mono { font-family:ui-monospace,'SF Mono',Menlo,Consolas,monospace;
  font-variant-numeric:tabular-nums; }
.top { position:sticky; top:0; z-index:5; background:rgba(7,10,18,.85);
  backdrop-filter:blur(10px); border-bottom:1px solid var(--line); padding:12px 20px; }
.topin { max-width:1140px; margin:0 auto; display:flex; align-items:center;
  gap:16px; flex-wrap:wrap; }
.brand { font-size:15px; font-weight:800; letter-spacing:.2px; }
.brand .zap { color:var(--teal); margin-right:2px; }
nav { display:flex; gap:2px; background:var(--panel); border:1px solid var(--line);
  border-radius:99px; padding:3px; }
nav a { color:var(--mut); text-decoration:none; font-size:12px; font-weight:650;
  padding:5px 14px; border-radius:99px; letter-spacing:.3px; }
nav a:hover { text-decoration:none; color:var(--ink); }
nav a.on { color:#051512;
  background:linear-gradient(120deg,var(--teal),#6FE8D2); }
.modes { margin-left:auto; display:flex; gap:8px; align-items:center; }
.pill { border:1px solid var(--line); border-radius:99px; padding:4px 11px;
  font-size:9.5px; font-weight:800; letter-spacing:1.5px; text-transform:uppercase; }
.pill.paper { color:var(--warn); border-color:#4a3a14; background:#171106; }
.pill.live { color:var(--gain); border-color:#14432f; background:#06180f; }
.pill.reg-risk_on { color:var(--gain); } .pill.reg-risk_off { color:var(--loss); }
.pill.reg-neutral { color:var(--mut); }
.wrap { max-width:1140px; margin:20px auto 0; padding:0 20px; display:flex;
  flex-direction:column; gap:16px; }
.kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; }
.kpi { background:linear-gradient(160deg,var(--panel2),var(--panel));
  border:1px solid var(--line); border-radius:12px; padding:14px 16px;
  box-shadow:0 1px 0 rgba(255,255,255,.04) inset, 0 10px 28px rgba(0,0,0,.35); }
.kpi .l { color:var(--dim); font-size:9.5px; font-weight:800; letter-spacing:1.7px;
  text-transform:uppercase; }
.kpi .v { font-size:24px; font-weight:750; margin-top:7px; letter-spacing:-.3px; }
.kpi .s { font-size:11px; color:var(--mut); margin-top:4px; }
.grid2 { display:grid; grid-template-columns:3fr 2fr; gap:16px; }
.grid2r { display:grid; grid-template-columns:2fr 3fr; gap:16px; }
@media (max-width:840px){ .grid2,.grid2r { grid-template-columns:1fr; } }
.panel { background:linear-gradient(160deg,var(--panel2),var(--panel));
  border:1px solid var(--line); border-radius:12px; padding:16px 18px;
  overflow-x:auto;
  box-shadow:0 1px 0 rgba(255,255,255,.04) inset, 0 10px 28px rgba(0,0,0,.35); }
.ph { display:flex; align-items:baseline; gap:10px; margin-bottom:12px; }
.ph h2 { color:var(--mut); font-size:10.5px; font-weight:800; letter-spacing:1.9px;
  text-transform:uppercase; }
.asof { margin-left:auto; color:var(--dim); font-size:10px; white-space:nowrap;
  font-family:ui-monospace,Menlo,monospace; }
table { width:100%; border-collapse:collapse; font-size:12.5px; }
th { text-align:left; color:var(--dim); font-size:9.5px; letter-spacing:1.4px;
  text-transform:uppercase; padding:7px 10px; border-bottom:1px solid var(--line); }
td { padding:8px 10px; border-bottom:1px solid #121A2C; vertical-align:top; }
tbody tr:hover td, tr:hover td { background:rgba(62,221,197,.03); }
tr:last-child td { border-bottom:none; }
.r { text-align:right; } th.r { text-align:right; }
.gain { color:var(--gain); } .loss { color:var(--loss); } .mut { color:var(--mut); }
.warn { color:var(--warn); }
.bar { height:6px; background:#121A2C; border-radius:3px; min-width:60px; }
.bar i { display:block; height:6px; border-radius:3px;
  background:linear-gradient(90deg,var(--teal),var(--violet)); }
.chips { display:flex; gap:6px; flex-wrap:wrap; }
.chip { border:1px solid var(--line); border-radius:99px; padding:2.5px 10px;
  font-size:11px; color:var(--mut); background:rgba(255,255,255,.02); }
.chip.pos { color:var(--gain); border-color:#14432f; }
.chip.neg { color:var(--loss); border-color:#4a2320; }
.chip.tick { color:var(--violet); border-color:#2d2657; }
.chip a { color:inherit; }
.note { font-size:12px; color:var(--mut); line-height:1.6; }
.klabel { color:var(--dim); font-size:10px; margin:12px 0 5px; letter-spacing:1.4px;
  text-transform:uppercase; font-weight:800; }
.ok { color:var(--gain); font-weight:700; } .no { color:var(--loss); font-weight:700; }
.newsit { padding:7px 0; border-bottom:1px solid #121A2C; }
.newsit:last-child { border-bottom:none; }
.newsit .t { font-size:12.5px; line-height:1.45; }
.newsit .m { font-size:10.5px; color:var(--dim); margin-top:2px;
  font-family:ui-monospace,Menlo,monospace; }
.foot { color:var(--dim); font-size:11px; text-align:center; margin-top:8px; line-height:1.9; }
.foot a { color:var(--mut); }
.schedwrap { max-width:1140px; margin:0 auto; padding:0 20px; }
.sched { display:flex; align-items:center; gap:9px; flex-wrap:wrap; margin-top:12px;
  padding:9px 14px; font-size:11.5px; border:1px solid var(--line); border-radius:10px;
  background:linear-gradient(160deg,var(--panel2),var(--panel));
  font-family:ui-monospace,Menlo,monospace; }
.sched .dot { width:8px; height:8px; border-radius:50%; background:var(--gain);
  box-shadow:0 0 0 0 rgba(61,220,151,.6); animation:pulse 2.4s infinite; }
.sched .dot.closed { background:var(--dim); animation:none; }
@keyframes pulse { 0%{box-shadow:0 0 0 0 rgba(61,220,151,.5)} 70%{box-shadow:0 0 0 7px rgba(61,220,151,0)} 100%{box-shadow:0 0 0 0 rgba(61,220,151,0)} }
.sched .sl { color:var(--dim); text-transform:uppercase; letter-spacing:1px; font-size:9.5px; font-weight:800; }
.sched .sv { color:var(--ink); font-weight:600; }
.sched .sv.soon { color:var(--teal); }
.sched .sv.now { color:var(--warn); }
.sched .sep { color:var(--line); }
.sched .barwrap { flex:1; min-width:80px; height:5px; background:#121A2C; border-radius:3px; overflow:hidden; }
.sched .barfill { display:block; height:5px; width:0;
  background:linear-gradient(90deg,var(--teal),var(--violet)); transition:width 1s linear; }
.alert { display:flex; gap:9px; padding:8px 0; border-bottom:1px solid #121A2C; align-items:flex-start; }
.alert:last-child { border-bottom:none; }
.alert .lv { font-size:9px; font-weight:800; letter-spacing:.6px; padding:2px 7px; border-radius:99px;
  text-transform:uppercase; white-space:nowrap; margin-top:1px; }
.alert .lv.info { color:var(--mut); border:1px solid var(--line); }
.alert .lv.warn { color:var(--warn); border:1px solid #4a3a14; background:#171106; }
.alert .lv.urgent { color:var(--loss); border:1px solid #4a2320; background:#180a09; }
.alert .body { font-size:12px; line-height:1.45; }
.alert .body .tk { color:var(--violet); font-weight:700; }
.alert .body .sr { color:var(--dim); font-size:10px; font-family:ui-monospace,Menlo,monospace; }
.sdot { display:inline-block; width:9px; height:9px; border-radius:50%; }
.sdot.green { background:var(--gain); box-shadow:0 0 6px rgba(61,220,151,.6); }
.sdot.red { background:var(--loss); box-shadow:0 0 6px rgba(255,122,112,.5); }
.sdot.grey { background:var(--dim); }
.sdot.run { background:var(--warn); animation:pulse 1.3s infinite; }
.rbar { height:5px; background:#121A2C; border-radius:3px; margin-top:5px; overflow:hidden; max-width:220px; }
.rbar i { display:block; height:5px; border-radius:3px;
  background:linear-gradient(90deg,var(--warn),var(--teal)); transition:width 1s linear; }
.mstrip { display:grid; grid-template-columns:repeat(auto-fit,minmax(120px,1fr)); gap:8px; }
.mtile { background:linear-gradient(180deg,#0C1422,#0A0F1B); border:1px solid var(--line);
  border-radius:8px; padding:9px 12px; }
.mtile .l { color:var(--dim); font-size:8.5px; font-weight:800; letter-spacing:1.4px; text-transform:uppercase; }
.mtile .v { font-size:15px; font-weight:700; margin-top:3px; }
.mtile .s { color:var(--dim); font-size:9.5px; margin-top:1px; }
.mktbar { max-width:1140px; margin:8px auto 0; padding:0 20px; }
.mkt { padding:8px 14px; border:1px solid var(--line); border-radius:10px;
  background:linear-gradient(160deg,#141d10,#0a0f0a); font-size:12.5px;
  font-family:ui-monospace,Menlo,monospace; color:var(--warn); text-align:center; }
.mkt.open { background:linear-gradient(160deg,#0a1a12,#071008); color:var(--gain); }
"""

MODE_RANK = {"risk_off": "risk off", "neutral": "neutral", "risk_on": "risk on"}


def _now_str():
    return dt.datetime.now().strftime("%a %d %b, %H:%M")


def _money(v, sign=False):
    """Compact currency: $8.0k, $1.2M, $940, −$3.7k. Keeps KPIs short."""
    s = "+" if (sign and v >= 0) else ("−" if v < 0 else "")
    a = abs(v)
    if a >= 1_000_000:
        body = "${:.2f}M".format(a / 1_000_000)
    elif a >= 10_000:
        body = "${:.1f}k".format(a / 1000)
    elif a >= 1_000:
        body = "${:,.0f}".format(a)
    else:
        body = "${:,.2f}".format(a)
    return s + body


def _load_health():
    """Workflow run statuses written by the scan workflow, or {}."""
    p = os.path.join(ROOT, "data", "health.json")
    if os.path.exists(p):
        try:
            with open(p) as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def _short(ts):
    return ts[5:16].replace("T", " ") if ts else "—"


def panel(title, asof, inner, extra=""):
    return ('<div class="panel"{x}><div class="ph"><h2>{t}</h2>'
            '<span class="asof">as of {a}</span></div>{i}</div>').format(
        t=title, a=asof, i=inner, x=extra)


def _page(active, body, cfg, research, gen, mood="flat"):
    regime = risk.regime(research)
    nav = "".join('<a href="{h}" class="{c}">{n}</a>'.format(
        h=h, c="on" if active == h else "", n=n)
        for h, n in (("index.html", "Overview"), ("radar.html", "Radar"),
                     ("history.html", "History")))
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<meta http-equiv="refresh" content="300"/>
<title>RobinHood Bot</title><style>{css}</style></head><body>
<canvas id="fx" aria-hidden="true"></canvas>
<div class="top"><div class="topin">
  <span class="brand"><span class="zap">&#9889;</span> RobinHood Bot</span>
  {nav}
  <span class="modes">
    <span class="pill {mc}">{mode}</span>
    <span class="pill reg-{reg}">{regt}</span>
  </span>
</div></div>
<div class="schedwrap"><div class="sched" id="sched">
  <span class="dot" id="scandot"></span>
  <span class="sl">Trading scan</span>
  <span class="sv" id="scan-next">—</span>
  <span class="sep">&middot;</span>
  <span class="sl">Hourly intel</span>
  <span class="sv" id="intel-next">—</span>
  <span class="sep">&middot;</span>
  <span class="sl">Daily research</span>
  <span class="sv" id="research-next">—</span>
  <span class="barwrap"><span class="barfill" id="hourbar"></span></span>
</div></div>
<div class="mktbar"><div class="mkt" id="mkt">checking the tape…</div></div>
<div class="wrap">{body}
<div class="foot">page generated {gen} &middot; browser auto-reloads every 5 min<br/>
scans hourly during US market hours &middot; hourly intel &middot; daily research &middot; weekly review</div>
</div>{sched}{fx}</body></html>""".format(
        css=CSS, nav=nav, body=body, gen=gen, fx=_fx_script(mood),
        sched=_sched_script(),
        mode=cfg["mode"], mc="live" if cfg["mode"] == "live" else "paper",
        reg=regime, regt=MODE_RANK[regime])


def _sched_script():
    """Live countdown to next scan/intel/research, computed in the viewer's
    local time from the known UTC cron schedules."""
    return """
<script>
(function(){
  // UTC schedules (minute past hour, list of UTC hours), weekdays only
  var SCANS={min:33,hours:[13,14,15,16,17,18,19,20,21]};
  var INTEL={min:8,hours:[14,15,16,17,18,19,20]};
  var RESEARCH={min:37,hours:[12]};
  function nextRun(s){
    var now=new Date();
    for(var d=0;d<5;d++){
      var day=new Date(now.getTime()+d*86400000);
      var dow=day.getUTCDay();
      if(dow===0||dow===6)continue;
      for(var i=0;i<s.hours.length;i++){
        var t=new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth(),day.getUTCDate(),s.hours[i],s.min,0));
        if(t>now)return t;
      }
    }
    return null;
  }
  function fmt(ms){
    if(ms<0)return"now";
    var m=Math.floor(ms/60000),h=Math.floor(m/60);m=m%60;
    if(h>0)return h+"h "+m+"m";
    var sec=Math.floor((ms%60000)/1000);
    return m+"m "+String(sec).padStart(2,"0")+"s";
  }
  function marketOpen(){
    var n=new Date(),h=n.getUTCHours(),day=n.getUTCDay();
    if(day===0||day===6)return false;
    var mins=h*60+n.getUTCMinutes();
    return mins>=13*60+30&&mins<20*60;  // ~9:30-16:00 ET in UTC (summer)
  }
  function tick(){
    var now=new Date();
    var defs=[["scan-next",SCANS],["intel-next",INTEL],["research-next",RESEARCH]];
    defs.forEach(function(d){
      var el=document.getElementById(d[0]);if(!el)return;
      var nx=nextRun(d[1]);if(!nx){el.textContent="—";return;}
      var ms=nx-now;el.textContent="in "+fmt(ms);
      el.className="sv"+(ms<120000?" now":(ms<600000?" soon":""));
    });
    var dot=document.getElementById("scandot");
    var open=marketOpen();
    if(dot)dot.className="dot"+(open?"":" closed");
    // WSB-style market countdown
    var mkt=document.getElementById("mkt");
    if(mkt){
      if(open){
        mkt.className="mkt open";
        var msgs=["🔔 market's OPEN — the casino is live 🎰",
          "🚀 bell's rung, let the tendies flow",
          "📈 stonks only go up (right?)",
          "💎🙌 hands ready, positions armed"];
        mkt.textContent=msgs[Math.floor(now.getTime()/60000)%msgs.length];
      }else{
        // next open = 9:30 ET. Compute via next SCANS-like 13:30/14:30 UTC weekday
        var openDef={min:30,hours:[13,14]}; // 9:30 ET summer(13:30 UTC)/winter(14:30)
        var nx=nextRun(openDef);
        var dow=now.getUTCDay();
        if(dow===0||dow===6){
          mkt.className="mkt";
          mkt.textContent="🛌 weekend — market closed. go touch grass, anon";
        }else if(nx){
          var ms=nx-now;
          mkt.className="mkt";
          mkt.textContent="⏰ market opens in "+fmt(ms)+" — "+
            (ms<1800000?"pre-market jitters incoming 😰":"time to do your DD (or don't) 🤡");
        }
      }
    }
    // progress bar = fraction through the current hour toward next scan
    var bar=document.getElementById("hourbar");
    if(bar){var nx=nextRun(SCANS);if(nx){var frac=1-((nx-now)/3600000);
      frac=Math.max(0,Math.min(1,frac));bar.style.width=(frac*100).toFixed(1)+"%";}}
  }
  tick();setInterval(tick,1000);
  // live-tick any currently-running workflow timers + progress bars
  var runbars=document.querySelectorAll(".rbar");
  function tickRuns(){
    runbars.forEach(function(b){
      var start=parseInt(b.getAttribute("data-start")||"0",10);
      var avg=parseInt(b.getAttribute("data-avg")||"0",10);
      start+=1;b.setAttribute("data-start",start);
      var i=b.querySelector("i");
      if(avg>0){i.style.width=Math.min(97,Math.round(100*start/avg))+"%";}
      var lbl=b.parentNode.childNodes[0];
      if(lbl&&lbl.nodeType===3){
        var m=Math.floor(start/60),s=start%60;
        lbl.textContent="running… "+(m>0?m+"m "+(s<10?"0":"")+s+"s":s+"s")+(avg>0?" / ~"+Math.floor(avg/60)+"m "+(avg%60<10?"0":"")+(avg%60)+"s":"");
      }
    });
  }
  if(runbars.length)setInterval(tickRuns,1000);
})();
</script>"""


def _fx_script(mood):
    """Ambient weather: gold coins rain when up, rain when down, calm when flat.
    Honors prefers-reduced-motion (renders nothing)."""
    return """
<style>#fx{position:fixed;inset:0;width:100vw;height:100vh;pointer-events:none;
z-index:1;opacity:.85}@media (prefers-reduced-motion:reduce){#fx{display:none}}</style>
<script>
(function(){
  var MOOD=""" + '"' + mood + '"' + """;
  if(MOOD==="flat")return;
  var m=window.matchMedia("(prefers-reduced-motion:reduce)");
  if(m.matches)return;
  var c=document.getElementById("fx"),x=c.getContext("2d"),W,H,P=[];
  function size(){W=c.width=innerWidth;H=c.height=innerHeight;}
  size();addEventListener("resize",size);
  var UP=MOOD==="up";
  var N=UP?Math.min(70,Math.floor(W/22)):Math.min(120,Math.floor(W/12));
  function coin(){return{x:Math.random()*W,y:Math.random()*-H,r:6+Math.random()*7,
    vy:1.6+Math.random()*2.4,sp:Math.random()*Math.PI,vs:0.05+Math.random()*0.12,
    sway:Math.random()*0.6};}
  function drop(){return{x:Math.random()*W,y:Math.random()*-H,len:10+Math.random()*16,
    vy:7+Math.random()*7,vx:-1.2};}
  for(var i=0;i<N;i++)P.push(UP?coin():drop());
  function draw(){
    x.clearRect(0,0,W,H);
    for(var i=0;i<P.length;i++){var p=P[i];
      if(UP){
        p.y+=p.vy;p.sp+=p.vs;p.x+=Math.sin(p.sp)*p.sway;
        var w=Math.abs(Math.cos(p.sp))*p.r+1.5;
        var g=x.createLinearGradient(p.x-w,p.y-p.r,p.x+w,p.y+p.r);
        g.addColorStop(0,"#FFE9A3");g.addColorStop(.5,"#F5C542");g.addColorStop(1,"#B8860B");
        x.beginPath();x.ellipse(p.x,p.y,w,p.r,0,0,7);x.fillStyle=g;x.fill();
        x.strokeStyle="rgba(120,80,0,.5)";x.lineWidth=1;x.stroke();
        if(w>p.r*0.55){x.fillStyle="rgba(120,80,0,.75)";x.font="bold "+(p.r)+"px ui-monospace,monospace";
          x.textAlign="center";x.textBaseline="middle";x.fillText("$",p.x,p.y+0.5);}
        if(p.y>H+p.r){P[i]=coin();P[i].y=-p.r;}
      }else{
        p.y+=p.vy;p.x+=p.vx;
        x.beginPath();x.moveTo(p.x,p.y);x.lineTo(p.x+p.vx*1.5,p.y+p.len);
        x.strokeStyle="rgba(120,160,220,.35)";x.lineWidth=1.4;x.stroke();
        if(p.y>H){P[i]=drop();P[i].y=-p.len;}
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
})();
</script>"""


# ---------------- data ----------------

def _realized_trades(trades_asc):
    """Pair sells with running cost basis -> list of closed-trade dicts."""
    book, closed = {}, []
    for ts, side, t, sh, price, value, mode, reason in trades_asc:
        if side == "buy":
            cur = book.get(t, (0, 0.0))
            n = cur[0] + sh
            book[t] = (n, (cur[0] * cur[1] + sh * price) / n if n else 0.0)
        else:
            n, avg = book.get(t, (0, price))
            pnl = (price - avg) * sh
            closed.append({"ts": ts, "ticker": t, "shares": sh, "buy": avg,
                           "sell": price, "pnl": pnl,
                           "pct": (price / avg - 1) * 100 if avg else 0,
                           "reason": (reason or "").split(";")[0][:60]})
            left = n - sh
            if left > 0:
                book[t] = (left, avg)
            else:
                book.pop(t, None)
    return closed


def _fetch_state():
    cfg = config.load()
    con = ledger.connect()
    now = _now_str()

    positions = []
    for p in ledger.open_positions(con):
        price = market.last_price(p["ticker"])
        positions.append({**p, "now": price,
                          "pl_pct": (price / p["avg_cost"] - 1) * 100 if price else None,
                          "pl_usd": (price - p["avg_cost"]) * p["shares"] if price else None})
    cash = ledger.cash(con)
    equity = cash + sum((p["now"] or p["avg_cost"]) * p["shares"] for p in positions)
    ledger.record_equity(con, equity, cash)
    con.commit()

    import re
    deposited = sum(float(m.group(1)) for (d,) in
                    con.execute("SELECT detail FROM decisions WHERE kind='deposit'")
                    if (m := re.search(r"\$([\d.]+)", d)))
    curve = con.execute("SELECT ts, equity FROM equity_history ORDER BY id").fetchall()
    trades_asc = con.execute("SELECT ts,side,ticker,shares,price,value,mode,reason "
                             "FROM trades ORDER BY id").fetchall()
    decisions = con.execute("SELECT ts,kind,detail FROM decisions "
                            "ORDER BY id DESC LIMIT 40").fetchall()
    cand_rows = con.execute("SELECT ts,ticker,score,detail FROM scan_candidates "
                            "ORDER BY id DESC LIMIT 24").fetchall()
    seen, candidates, cand_ts = set(), [], None
    for ts, t, s, d in cand_rows:
        cand_ts = cand_ts or ts
        if t not in seen:
            seen.add(t)
            candidates.append((t, s, json.loads(d)))
    candidates = sorted(candidates[:8], key=lambda c: c[1], reverse=True)
    rewards = con.execute("SELECT signal, COUNT(*), AVG(pnl_pct) FROM signal_rewards "
                          "WHERE contribution > 0.2 GROUP BY signal").fetchall()
    buys_wk = ledger.buys_this_week(con)
    con.close()

    intel = risk.load_intel()
    from bot.signals.reddit import fetch_mentions
    reddit = fetch_mentions()

    news, seen_n = [], set()
    for t in [p["ticker"] for p in positions] + [c[0] for c in candidates[:3]]:
        if t in seen_n:
            continue
        seen_n.add(t)
        for item in market.ticker_news(t)[:2]:
            c = item.get("content") or {}
            title = c.get("title") or item.get("title")
            url = ((c.get("clickThroughUrl") or {}).get("url")
                   or (c.get("canonicalUrl") or {}).get("url") or "")
            if title:
                news.append({"ticker": t, "title": title, "url": url,
                             "src": (c.get("provider") or {}).get("displayName") or "",
                             "when": (c.get("pubDate") or "")[:16].replace("T", " ")})

    research = risk.load_research()
    return {
        "cfg": cfg, "now": now, "positions": positions, "cash": cash,
        "equity": equity, "deposited": deposited, "curve": curve,
        "trades_asc": trades_asc, "closed": _realized_trades(trades_asc),
        "decisions": decisions, "candidates": candidates,
        "cand_ts": _short(cand_ts), "rewards": rewards,
        "buys_wk": buys_wk, "research": research,
        "reddit": reddit, "news": news, "intel": intel,
    }


# ---------------- charts ----------------

def _equity_svg(curve, deposited, w=640, h=190):
    if not curve:
        return '<div class="mut">no equity history yet</div>'
    pts = [e for _, e in curve]
    if len(pts) == 1:
        pts = pts * 2
    pad, padb = 10, 22
    lo = min(pts + ([deposited] if deposited else []))
    hi = max(pts + ([deposited] if deposited else []))
    if hi - lo < 1:
        lo, hi = lo - 1, hi + 1
    def x(i): return pad + i * (w - 2 * pad) / (len(pts) - 1)
    def y(v): return (h - padb) - (v - lo) * (h - padb - pad) / (hi - lo)
    line = " ".join("{:.1f},{:.1f}".format(x(i), y(v)) for i, v in enumerate(pts))
    area = "{},{} {} {},{}".format(x(0), h - padb, line, x(len(pts) - 1), h - padb)
    color = "#34D399" if (not deposited or pts[-1] >= deposited) else "#F87171"
    grid = "".join('<line x1="{p}" y1="{gy:.1f}" x2="{w2}" y2="{gy:.1f}" '
                   'stroke="#131D30" stroke-width="1"/>'.format(
                       p=pad, w2=w - pad, gy=(h - padb) - k * (h - padb - pad) / 4)
                   for k in range(1, 5))
    dep = ""
    if deposited:
        dep = ('<line x1="{p}" y1="{dy:.1f}" x2="{w2}" y2="{dy:.1f}" stroke="#7E8CA6" '
               'stroke-dasharray="4 4" opacity="0.6"/>').format(
            p=pad, w2=w - pad, dy=y(deposited))
    d0, d1 = curve[0][0][:10], curve[-1][0][:10]
    return ('<svg viewBox="0 0 {w} {h}" width="100%" role="img" aria-label="equity">'
            '<defs><linearGradient id="eq" x1="0" y1="0" x2="0" y2="1">'
            '<stop offset="0%" stop-color="{c}" stop-opacity="0.25"/>'
            '<stop offset="100%" stop-color="{c}" stop-opacity="0"/></linearGradient></defs>'
            '{grid}{dep}<polygon points="{area}" fill="url(#eq)"/>'
            '<polyline points="{line}" fill="none" stroke="{c}" stroke-width="2"/>'
            '<circle cx="{cx:.1f}" cy="{cy:.1f}" r="3.5" fill="{c}"/>'
            '<text x="{p}" y="{h2}" fill="#5A6A87" font-size="9" font-family="Menlo,monospace">{d0}</text>'
            '<text x="{w2}" y="{h2}" fill="#5A6A87" font-size="9" text-anchor="end" font-family="Menlo,monospace">{d1}</text>'
            '<text x="{p}" y="{ty:.1f}" fill="#5A6A87" font-size="9" font-family="Menlo,monospace">${hi:,.0f}</text>'
            '<text x="{p}" y="{by:.1f}" fill="#5A6A87" font-size="9" font-family="Menlo,monospace">${lo:,.0f}</text>'
            '</svg>').format(w=w, h=h, c=color, grid=grid, dep=dep, area=area,
                             line=line, cx=x(len(pts) - 1), cy=y(pts[-1]), p=pad,
                             w2=w - pad, h2=h - 6, d0=d0, d1=d1,
                             ty=y(hi) + 10, by=y(lo) - 3, hi=hi, lo=lo)


def _sparkline(closes, cost=None, w=88, h=26):
    """Tiny inline SVG price line; green if last>=first, red otherwise. If cost
    is given, a faint dashed line marks the entry price."""
    if not closes or len(closes) < 2:
        return '<span class="mut" style="font-size:10px">no data</span>'
    lo, hi = min(closes), max(closes)
    if cost:
        lo, hi = min(lo, cost), max(hi, cost)
    rng = (hi - lo) or 1
    pad = 2
    def x(i): return pad + i * (w - 2 * pad) / (len(closes) - 1)
    def y(v): return (h - pad) - (v - lo) * (h - 2 * pad) / rng
    pts = " ".join("{:.1f},{:.1f}".format(x(i), y(v)) for i, v in enumerate(closes))
    up = closes[-1] >= closes[0]
    color = "#3DDC97" if up else "#FF7A70"
    cost_line = ""
    if cost:
        cost_line = ('<line x1="{p}" y1="{cy:.1f}" x2="{w2}" y2="{cy:.1f}" '
                     'stroke="#5C6B8C" stroke-width="0.7" stroke-dasharray="2 2" '
                     'opacity="0.7"/>').format(p=pad, w2=w - pad, cy=y(cost))
    return ('<svg viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
            'style="vertical-align:middle">{cl}<polyline points="{pts}" fill="none" '
            'stroke="{c}" stroke-width="1.4"/>'
            '<circle cx="{cx:.1f}" cy="{cy:.1f}" r="1.8" fill="{c}"/></svg>').format(
        w=w, h=h, cl=cost_line, pts=pts, c=color, cx=x(len(closes) - 1),
        cy=y(closes[-1]))


def _period_stats(closed):
    """Realized P/L + averages for today / this week / this month."""
    today = dt.date.today()
    monday = today - dt.timedelta(days=today.weekday())
    month1 = today.replace(day=1)
    buckets = {"Day": [], "Week": [], "Month": [], "All time": []}
    for t in closed:
        d = dt.date.fromisoformat(t["ts"][:10])
        buckets["All time"].append(t)
        if d >= month1:
            buckets["Month"].append(t)
        if d >= monday:
            buckets["Week"].append(t)
        if d == today:
            buckets["Day"].append(t)
    rows = []
    for label, ts in buckets.items():
        wins = [t for t in ts if t["pnl"] > 0]
        losses = [t for t in ts if t["pnl"] <= 0]
        net = sum(t["pnl"] for t in ts)
        avg_w = sum(t["pct"] for t in wins) / len(wins) if wins else 0
        avg_l = sum(t["pct"] for t in losses) / len(losses) if losses else 0
        nc = "gain" if net >= 0 else "loss"
        rows.append(
            '<tr><td class="mono">{lb}</td><td class="mono r">{n}</td>'
            '<td class="mono r {nc}">{ns}${na:,.2f}</td>'
            '<td class="mono r gain">{aw}</td><td class="mono r loss">{al}</td></tr>'.format(
                lb=label, n=len(ts), nc=nc, ns="+" if net >= 0 else "−", na=abs(net),
                aw="+{:.1f}%".format(avg_w) if wins else "—",
                al="{:.1f}%".format(avg_l) if losses else "—"))
    return ('<table><tr><th>Window</th><th class="r">Trades</th><th class="r">Net P/L</th>'
            '<th class="r">Avg win</th><th class="r">Avg loss</th></tr>{}</table>'.format(
                "".join(rows)))


# WSB-flavoured captions, chosen by trade outcome
FAME_CAPS = [
    ("🚀", "TO THE MOON"), ("💎🙌", "diamond hands paid off"),
    ("🤑", "tendies secured"), ("📈", "absolute stonks"),
    ("🧠", "big brain play"), ("🍗", "fat tendies"),
]
SHAME_CAPS = [
    ("💀", "GUH"), ("📉", "bought the top, sold the bottom"),
    ("🧻🙌", "paper hands special"), ("🤡", "clown market got us"),
    ("🎒", "certified bagholder"), ("🔥", "this is fine"),
]


def _hall(closed):
    if not closed:
        return ('<div class="mut">no closed trades yet — the halls await their first '
                'legends and cautionary tales 🫡</div>')
    best = sorted(closed, key=lambda t: t["pct"], reverse=True)[:3]
    worst = sorted(closed, key=lambda t: t["pct"])[:3]

    def card(t, caps, i, good):
        emoji, cap = caps[i % len(caps)]
        cls = "gain" if good else "loss"
        held = ""
        try:
            held = "{}d".format((dt.date.fromisoformat(t["ts"][:10])
                                 - dt.date.fromisoformat(t["ts"][:10])).days)
        except Exception:
            pass
        return (
            '<div style="border:1px solid var(--line);border-radius:10px;padding:11px 13px;'
            'background:rgba(255,255,255,.02)">'
            '<div style="font-size:20px">{e}</div>'
            '<div class="mono" style="font-size:15px;font-weight:800;margin:3px 0">'
            '<span class="tk" style="color:var(--violet)">{tk}</span> '
            '<span class="{cls}">{ps}{pct:.1f}%</span></div>'
            '<div class="note" style="font-size:11px">{cap}</div>'
            '<div class="mono" style="font-size:10.5px;color:var(--dim);margin-top:3px">'
            '${b:.2f} → ${s:.2f} · {ns}${amt:,.2f}</div></div>').format(
            e=emoji, tk=t["ticker"], cls=cls, ps="+" if t["pct"] >= 0 else "",
            pct=t["pct"], cap=cap, b=t["buy"], s=t["sell"],
            ns="+" if t["pnl"] >= 0 else "−", amt=abs(t["pnl"]))

    fame = "".join(card(t, FAME_CAPS, i, True) for i, t in enumerate(best))
    shame = "".join(card(t, SHAME_CAPS, i, False) for i, t in enumerate(worst))
    grid = ('display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px')
    return (
        '<div class="klabel" style="color:var(--gain)">🏆 Hall of Fame — biggest tendies</div>'
        '<div style="{g}">{fame}</div>'
        '<div class="klabel" style="color:var(--loss);margin-top:14px">🤡 Hall of Shame — '
        'lessons in humility</div><div style="{g}">{shame}</div>').format(
        g=grid, fame=fame, shame=shame)


def _weekly_bars(closed, w=520, h=150):
    if not closed:
        return '<div class="mut">no closed trades yet</div>'
    weeks = {}
    for t in closed:
        wk = "{}-W{:02d}".format(*dt.date.fromisoformat(t["ts"][:10]).isocalendar()[:2])
        weeks[wk] = weeks.get(wk, 0) + t["pnl"]
    keys = sorted(weeks)[-12:]
    vals = [weeks[k] for k in keys]
    mx = max(abs(v) for v in vals) or 1
    bw = (w - 20) / max(len(keys), 1)
    mid = h / 2
    bars = []
    for i, (k, v) in enumerate(zip(keys, vals)):
        bh = abs(v) / mx * (mid - 18)
        ycoord = mid - bh if v >= 0 else mid
        c = "#34D399" if v >= 0 else "#F87171"
        bars.append('<rect x="{x:.1f}" y="{y:.1f}" width="{bw:.1f}" height="{bh:.1f}" '
                    'rx="2" fill="{c}"/>'
                    '<text x="{tx:.1f}" y="{h2}" fill="#5A6A87" font-size="8" '
                    'text-anchor="middle" font-family="Menlo,monospace">{lbl}</text>'.format(
                        x=10 + i * bw + 2, y=ycoord, bw=bw - 4, bh=max(bh, 1), c=c,
                        tx=10 + i * bw + bw / 2, h2=h - 4, lbl=k[-3:]))
    return ('<svg viewBox="0 0 {w} {h}" width="100%"><line x1="10" y1="{m}" x2="{w2}" '
            'y2="{m}" stroke="#1B2740"/>{bars}</svg>').format(
        w=w, h=h, m=mid, w2=w - 10, bars="".join(bars))


# ---------------- page bodies ----------------

def _extra_metrics(st):
    """Second-row stat strip: exposure, streak, avg hold, best/worst day, etc."""
    closed = st["closed"]
    positions = st["positions"]
    invested = sum((p["now"] or p["avg_cost"]) * p["shares"] for p in positions)
    exposure = (invested / st["equity"] * 100) if st["equity"] else 0

    # win/loss streak (most recent closed trades)
    streak, streak_kind = 0, None
    for t in reversed(closed):
        k = "W" if t["pnl"] > 0 else "L"
        if streak_kind is None:
            streak_kind = k
        if k == streak_kind:
            streak += 1
        else:
            break
    streak_txt = "—" if not closed else "{}{} {}".format(
        streak, streak_kind, "🔥" if streak_kind == "W" and streak >= 2
        else ("🧊" if streak_kind == "L" and streak >= 2 else ""))

    # P/L by calendar day → best/worst day
    by_day = {}
    for t in closed:
        by_day[t["ts"][:10]] = by_day.get(t["ts"][:10], 0) + t["pnl"]
    best_day = max(by_day.values()) if by_day else 0
    worst_day = min(by_day.values()) if by_day else 0

    total_ret = (st["equity"] / st["deposited"] - 1) * 100 if st["deposited"] else 0
    tot_cls = "gain" if total_ret >= 0 else "loss"

    tiles = [
        ("Total return", "{:+.1f}%".format(total_ret), tot_cls,
         "since first deposit"),
        ("Exposure", "{:.0f}%".format(exposure),
         "warn" if exposure > 90 else "mut", "invested vs cash"),
        ("Positions", "{}/{}".format(len(positions), st["cfg"]["buying"]["max_positions"]),
         "mut", "slots used"),
        ("Streak", streak_txt, "gain" if streak_kind == "W" else ("loss" if streak_kind == "L" else "mut"),
         "recent closes"),
        ("Best day", _money(best_day, sign=True), "gain", "single-day P/L"),
        ("Worst day", _money(worst_day, sign=True), "loss", "single-day P/L"),
    ]
    cells = "".join(
        '<div class="mtile"><div class="l">{l}</div><div class="v mono {c}">{v}</div>'
        '<div class="s">{s}</div></div>'.format(l=l, v=v, c=c, s=s)
        for l, v, c, s in tiles)
    return '<div class="mstrip">{}</div>'.format(cells)


def _kpis(st):
    unreal = sum(p["pl_usd"] or 0 for p in st["positions"])
    net = st["equity"] - st["deposited"] if st["deposited"] else 0.0
    realized = sum(t["pnl"] for t in st["closed"])
    def cls(v): return "gain" if v >= 0 else "loss"
    def sgn(v): return "+" if v >= 0 else "−"
    return """<div class="kpis">
<div class="kpi"><div class="l">Total equity</div><div class="v mono" title="${eqf:,.2f}">{eq}</div><div class="s">deposited {dep}</div></div>
<div class="kpi"><div class="l">Cash</div><div class="v mono" title="${cashf:,.2f}">{cash}</div><div class="s">{np} open position(s)</div></div>
<div class="kpi"><div class="l">Net P/L</div><div class="v mono {nc}">{net}</div><div class="s">vs deposits</div></div>
<div class="kpi"><div class="l">Unrealized</div><div class="v mono {uc}">{ur}</div><div class="s">open positions</div></div>
<div class="kpi"><div class="l">Realized</div><div class="v mono {rc}">{rl}</div><div class="s">{nt} closed trade(s)</div></div>
</div>""".format(eq=_money(st["equity"]), eqf=st["equity"], dep=_money(st["deposited"]),
                 cash=_money(st["cash"]), cashf=st["cash"], np=len(st["positions"]),
                 nc=cls(net), net=_money(net, sign=True),
                 uc=cls(unreal), ur=_money(unreal, sign=True),
                 rc=cls(realized), rl=_money(realized, sign=True),
                 nt=len(st["closed"]))


def _positions_panel(st):
    cfg, research = st["cfg"], st["research"]
    stop_pct = risk.dynamic_stop_pct(cfg, 0, research)
    tp = cfg["selling"]["take_profit_pct"]
    if not st["positions"]:
        inner = '<div class="mut">flat — no open positions</div>'
    else:
        rows = []
        for p in st["positions"]:
            hwm = max(p["high_water_mark"] or 0, p["now"] or 0)
            stop_lvl = hwm * (1 - stop_pct / 100)
            tp_lvl = p["avg_cost"] * (1 + tp / 100)
            cls = "mut" if p["pl_pct"] is None else ("gain" if p["pl_pct"] >= 0 else "loss")
            spark = _sparkline(market.price_series(p["ticker"]), cost=p["avg_cost"])
            pl_usd = "" if p["pl_usd"] is None else " <span class='mut' style='font-size:10.5px'>({}${:,.0f})</span>".format(
                "+" if p["pl_usd"] >= 0 else "−", abs(p["pl_usd"]))
            rows.append(
                '<tr><td class="mono"><b>{t}</b></td><td>{spark}</td>'
                '<td class="mono r">{sh}</td>'
                '<td class="mono r">${c:.2f}</td><td class="mono r">{n}</td>'
                '<td class="mono r {cls}">{pct}{plu}</td>'
                '<td class="mono r loss">${sl:.2f}</td><td class="mono r gain">${tl:.2f}</td></tr>'.format(
                    t=p["ticker"], spark=spark, sh=p["shares"], c=p["avg_cost"],
                    n="${:.2f}".format(p["now"]) if p["now"] else "—", cls=cls,
                    pct="{:+.1f}%".format(p["pl_pct"]) if p["pl_pct"] is not None else "—",
                    plu=pl_usd, sl=stop_lvl, tl=tp_lvl))
        inner = ('<table><tr><th>Ticker</th><th>30d</th><th class="r">Qty</th><th class="r">Avg</th>'
                 '<th class="r">Now</th><th class="r">P/L</th><th class="r">Sells below</th>'
                 '<th class="r">Target</th></tr>{}</table>'
                 '<div class="note" style="margin-top:8px">"Sells below" is the trailing '
                 'stop from the high-water mark at the current ~{:.0f}% stop; it rises as '
                 'the price does. Target is the +{:.0f}% take-profit.</div>').format(
            "".join(rows), stop_pct, tp)
    return panel("Open positions &amp; exit map", "prices " + st["now"], inner)


def _candidates_panel(st, threshold):
    if not st["candidates"]:
        return panel("Scan candidates", st["cand_ts"],
                     '<div class="mut">no candidates in the last scan</div>')
    top = max(c[1] for c in st["candidates"]) or 1
    rows = []
    for t, s, d in st["candidates"]:
        verdict = ('<span class="ok">&#10003; above threshold</span>' if s >= threshold
                   else '<span class="mut">below {}</span>'.format(threshold))
        parts = ", ".join("{} {}".format(k, v) for k, v in (d.get("parts") or {}).items())
        r = (st.get("reddit") or {}).get(t)
        if r:
            parts += (' &middot; <a href="https://apewisdom.io/stocks/{t}/" target="_blank" '
                      'rel="noopener">reddit {m} mentions, rank {rk}</a>').format(
                t=t, m=r["mentions"], rk=r.get("rank", "—"))
        else:
            parts += " &middot; reddit: quiet"
        parts += (' &middot; <a href="https://www.reddit.com/search/?q=%24{t}&sort=new" '
                  'target="_blank" rel="noopener">posts &#8599;</a>').format(t=t)
        rows.append(
            '<tr><td class="mono"><b>{t}</b><div class="mut" style="font-size:10.5px">{name}</div></td>'
            '<td class="mono r">{price}</td>'
            '<td style="width:110px;padding-top:12px"><div class="bar"><i style="width:{w:.0f}%"></i></div></td>'
            '<td class="mono r">{s}</td><td>{v}</td></tr>'
            '<tr><td colspan="5" class="mut" style="font-size:10.5px;padding-top:0">{parts}</td></tr>'.format(
                t=t, name=(d.get("name") or "")[:32],
                price="${:.2f}".format(d["price"]) if d.get("price") else "—",
                w=100 * s / top, s=s, v=verdict, parts=parts))
    return panel("Scan candidates", "scan " + st["cand_ts"],
                 '<table><tr><th>Ticker</th><th class="r">Price</th><th>Score</th>'
                 '<th class="r"></th><th></th></tr>{}</table>'.format("".join(rows)))


def _research_panel(st):
    research = st["research"]
    if not research or research.get("_stale"):
        return panel("Research", research.get("date", "—"),
                     '<div class="mut">no fresh research — quant regime only</div>')
    bias = research.get("sector_bias", {})
    chips = "".join('<span class="chip {c}">{s} {v:+.1f}</span>'.format(
        c="pos" if v > 0 else "neg", s=s, v=v) for s, v in bias.items())
    watch = "".join('<span class="chip tick">{}</span>'.format(t)
                    for t in risk.watchlist_tickers(research)) or '<span class="mut">—</span>'
    avoid = "".join('<span class="chip neg">{}</span>'.format(t)
                    for t in sorted(risk.avoid_tickers(research))) or '<span class="mut">—</span>'
    inner = ('<div class="note">{reason}</div>'
             '<div class="klabel">Sector bias</div><div class="chips">{chips}</div>'
             '<div class="klabel">Watchlist</div><div class="chips">{w}</div>'
             '<div class="klabel">Avoid</div><div class="chips">{a}</div>'
             '<div class="klabel">Notes</div><div class="note">{n}</div>').format(
        reason=research.get("regime_reason", ""), chips=chips or '<span class="mut">none</span>',
        w=watch, a=avoid, n=research.get("notes", ""))
    return panel("Daily research", research.get("date", "—"), inner)


def _news_panel(st):
    if not st["news"]:
        inner = '<div class="mut">no recent headlines for held or candidate tickers</div>'
    else:
        inner = "".join(
            '<div class="newsit"><div class="t"><span class="chip tick">{t}</span> '
            '{link}</div><div class="m">{src}{sep}{when}</div></div>'.format(
                t=n["ticker"],
                link='<a href="{u}" target="_blank" rel="noopener">{h}</a>'.format(
                    u=n["url"], h=n["title"]) if n["url"] else n["title"],
                src=n["src"], sep=" &middot; " if n["src"] and n["when"] else "",
                when=n["when"])
            for n in st["news"][:10])
    return panel("Headlines the bot is reading", "fetched " + st["now"], inner)


def _intel_panel(st):
    intel = st.get("intel") or {}
    if not intel or intel.get("_stale"):
        note = ("last intel {} — stale, awaiting next hourly run".format(
            intel.get("generated", "")[:16].replace("T", " ")) if intel.get("_stale")
            else "no hourly intel yet — runs every hour during US market hours")
        return panel("Live intel feed", "hourly", '<div class="mut">{}</div>'.format(note))
    tape = intel.get("tape", "")
    alerts = intel.get("alerts", [])[:12]
    if alerts:
        items = "".join(
            '<div class="alert"><span class="lv {lv}">{lv}</span>'
            '<div class="body"><span class="tk">{tk}</span> {hl}'
            '{link}<div class="sr">{time}</div></div></div>'.format(
                lv=(a.get("level") or "info"), tk=a.get("ticker", ""),
                hl=a.get("headline", ""),
                link=' &middot; <a href="{u}" target="_blank" rel="noopener">source &#8599;</a>'.format(
                    u=a["source"]) if a.get("source", "").startswith("http") else "",
                time=a.get("time", ""))
            for a in alerts)
    else:
        items = '<div class="mut">no material alerts this hour</div>'
    gen = intel.get("generated", "")[:16].replace("T", " ")
    tape_html = ('<div class="note" style="margin-bottom:10px;color:var(--ink)">'
                 '<b style="color:var(--dim)">TAPE:</b> {}</div>'.format(tape)) if tape else ""
    return panel("Live intel feed", "intel " + gen + " UTC", tape_html + items)


WORKFLOW_LABELS = [
    ("trading-scan", "Trading scans"), ("hourly-intel", "Hourly intel"),
    ("daily-research", "Daily research"), ("weekly-review", "Weekly review"),
    ("backtest", "Backtest"),
]


def _fmt_dur(s):
    if s is None:
        return ""
    if s < 60:
        return "{}s".format(s)
    return "{}m {:02d}s".format(s // 60, s % 60)


def _github_panel(st):
    health = _load_health()
    runs = health.get("workflows", {})
    rows = []
    for key, label in WORKFLOW_LABELS:
        info = runs.get(key)
        if not info:
            dot, cls, txt, bar = "grey", "", "not run yet", ""
        else:
            status = info.get("status")
            concl = info.get("conclusion")
            when = info.get("when", "")[5:16].replace("T", " ")
            if status in ("in_progress", "queued"):
                # RUNNING: pulsing amber + live elapsed, progress vs avg duration
                run_s = info.get("running_s", 0)
                avg = info.get("avg_s")
                pct = min(95, int(100 * run_s / avg)) if avg else 40
                dot, cls = "run", "warn"
                txt = ("running… {}".format(_fmt_dur(run_s)) +
                       (" / ~{}".format(_fmt_dur(avg)) if avg else ""))
                bar = ('<div class="rbar" data-start="{}" data-avg="{}">'
                       '<i style="width:{}%"></i></div>').format(run_s, avg or 0, pct)
            elif concl == "success":
                dot, cls = "green", "gain"
                txt = "OK · {} · ran in {}".format(when, _fmt_dur(info.get("duration_s")))
                bar = ""
            elif concl in ("skipped", None):
                dot, cls, txt, bar = "grey", "mut", "{} · {}".format(concl or "idle", when), ""
            else:
                dot, cls = "red", "loss"
                txt = "{} · {} · {}".format(concl, when, _fmt_dur(info.get("duration_s")))
                bar = ""
        rows.append('<tr><td style="width:14px"><span class="sdot {d}"></span></td>'
                    '<td class="mono" style="white-space:nowrap">{lb}</td>'
                    '<td class="note {c}">{t}{bar}</td></tr>'.format(
                        d=dot, lb=label, c=cls, t=txt, bar=bar))
    updated = health.get("generated", "")[:16].replace("T", " ")
    note = ('<div class="note" style="margin-top:8px">🟢 last run OK · 🔴 failed · '
            '🟡 running now (live timer) · grey = idle/not-run. Durations are actual '
            'run times.</div>')
    return panel("Running on GitHub", "status " + (updated or "—"),
                 '<table>{}</table>{}'.format("".join(rows), note))


def _overview(st):
    threshold = risk.buy_threshold(st["cfg"], st["research"])
    trades = list(reversed(st["trades_asc"][-6:]))
    trows = "".join(
        '<tr><td class="mono mut">{d}</td><td class="mono {c}"><b>{side}</b></td>'
        '<td class="mono"><b>{t}</b></td><td class="mono r">{sh}</td>'
        '<td class="mono r">${p:.2f}</td></tr>'.format(
            d=_short(ts), c="gain" if side == "buy" else "loss", side=side.upper(),
            t=t, sh=sh, p=price)
        for ts, side, t, sh, price, *_ in trades) or \
        '<tr><td class="mut">no trades yet</td></tr>'
    body = _kpis(st)
    body += _extra_metrics(st)
    body += '<div class="grid2">'
    body += panel("Equity curve", "snapshot " + st["now"],
                  _equity_svg(st["curve"], st["deposited"]))
    body += _research_panel(st)
    body += "</div>"
    body += '<div class="grid2">'
    body += _github_panel(st)
    body += _intel_panel(st)
    body += "</div>"
    body += _positions_panel(st)
    body += '<div class="grid2">'
    body += _news_panel(st)
    body += panel("Recent trades", "ledger " + st["now"],
                  '<table><tr><th>When</th><th>Side</th><th>Ticker</th>'
                  '<th class="r">Qty</th><th class="r">Price</th></tr>{}</table>'
                  '<div class="note" style="margin-top:8px"><a href="history.html" '
                  'style="color:var(--teal)">full history &rarr;</a></div>'.format(trows))
    body += "</div>"
    body += _candidates_panel(st, threshold)
    return body


def _radar(st):
    cfg, research = st["cfg"], st["research"]
    threshold = risk.buy_threshold(cfg, research)
    buy_cfg = cfg["buying"]
    halted = None
    con = ledger.connect()
    halted = risk.trading_halted(con, cfg)
    con.close()

    # next-buy conditions checklist
    checks = []
    def add(okv, txt):
        checks.append('<tr><td>{}</td><td class="note">{}</td></tr>'.format(
            '<span class="ok">&#10003;</span>' if okv else '<span class="no">&#10007;</span>', txt))
    add(halted is None, "circuit breakers clear" + (": <b>{}</b>".format(halted) if halted else ""))
    add(st["buys_wk"] < buy_cfg["max_buys_per_week"],
        "weekly buy budget: {}/{} used (resets Monday)".format(st["buys_wk"], buy_cfg["max_buys_per_week"]))
    add(len(st["positions"]) < buy_cfg["max_positions"],
        "position slots: {}/{} filled".format(len(st["positions"]), buy_cfg["max_positions"]))
    top_ok = bool(st["candidates"]) and st["candidates"][0][1] >= threshold
    add(top_ok, "top candidate {} threshold {} (regime-adjusted)".format(
        "meets" if top_ok else "below", threshold))
    add(st["cash"] > 1, "cash available: ${:,.2f}".format(st["cash"]))
    next_dep = (dt.date.today().replace(day=1) + dt.timedelta(days=32)).replace(day=1)
    cond = panel("Will it buy next scan?", st["now"],
                 '<table>{}</table><div class="note" style="margin-top:8px">All checks must '
                 'pass, then the top candidate still faces the confluence gate (volume, VWAP, '
                 'spread, IV, dilution, pump &amp; earnings vetoes) at execution time. '
                 'Next deposit: {}.</div>'.format("".join(checks), next_dep))

    watch = _candidates_panel(st, threshold)

    # exit radar per position
    stop_pct = risk.dynamic_stop_pct(cfg, 0, research)
    sell_cfg = cfg["selling"]
    rows = []
    for p in st["positions"]:
        held = (dt.datetime.now(dt.timezone.utc)
                - dt.datetime.fromisoformat(p["opened_at"])).days
        hwm = max(p["high_water_mark"] or 0, p["now"] or 0)
        rows.append('<tr><td class="mono"><b>{t}</b></td>'
                    '<td class="mono r">day {d}/{mx}</td>'
                    '<td class="mono r loss">${sl:.2f}</td>'
                    '<td class="mono r gain">${tl:.2f}</td>'
                    '<td class="note">{note}</td></tr>'.format(
                        t=p["ticker"], d=held, mx=sell_cfg["max_hold_days"],
                        sl=hwm * (1 - stop_pct / 100),
                        tl=p["avg_cost"] * (1 + sell_cfg["take_profit_pct"] / 100),
                        note="min hold {}d not met — stop armed day {}".format(
                            sell_cfg["min_hold_days"], sell_cfg["min_hold_days"])
                        if held < sell_cfg["min_hold_days"] else "stop live, trails the high"))
    exits = panel("Exit radar", "prices " + st["now"],
                  '<table><tr><th>Held</th><th class="r">Clock</th><th class="r">Sells below</th>'
                  '<th class="r">Target</th><th>Status</th></tr>{}</table>'.format(
                      "".join(rows)) if rows else '<div class="mut">flat — nothing to exit</div>')

    # learning progress
    lc = cfg["learning"]
    lr = []
    for sig, n, avg in st["rewards"]:
        pc = min(100, 100 * n / lc["min_trades_per_signal"])
        lr.append('<tr><td class="mono">{s}</td><td style="width:110px;padding-top:11px">'
                  '<div class="bar"><i style="width:{p:.0f}%"></i></div></td>'
                  '<td class="mono r">{n}/{need}</td><td class="mono r {c}">{avg:+.1f}%</td></tr>'.format(
                      s=sig, p=pc, n=n, need=lc["min_trades_per_signal"],
                      c="gain" if avg >= 0 else "loss", avg=avg))
    learn = panel("Signal learning progress", "ledger " + st["now"],
                  ('<table><tr><th>Signal</th><th>Evidence</th><th class="r">Trades</th>'
                   '<th class="r">Avg P/L</th></tr>{}</table>'
                   '<div class="note" style="margin-top:8px">Weights adjust &plusmn;{}% monthly '
                   'once a signal has {} closed trades, clamped to {}&ndash;{}% of defaults.</div>'
                   ).format("".join(lr), lc["nudge_pct"], lc["min_trades_per_signal"],
                            int(lc["weight_floor_x"] * 100), int(lc["weight_ceil_x"] * 100))
                  if lr else
                  '<div class="mut">no closed trades yet — rewards accrue when positions close</div>')

    return cond + '<div class="grid2">' + watch + exits + "</div>" + \
        '<div class="grid2r">' + learn + _research_panel(st) + "</div>"


def _history(st):
    closed = list(reversed(st["closed"]))
    crows = "".join(
        '<tr><td class="mono mut">{d}</td><td class="mono"><b>{t}</b></td>'
        '<td class="mono r">{sh}</td><td class="mono r">${b:.2f}</td>'
        '<td class="mono r">${s:.2f}</td><td class="mono r {c}">{ps}${pa:,.2f}</td>'
        '<td class="mono r {c}">{pct:+.1f}%</td><td class="note">{r}</td></tr>'.format(
            d=_short(t["ts"]), t=t["ticker"], sh=t["shares"], b=t["buy"], s=t["sell"],
            c="gain" if t["pnl"] >= 0 else "loss", ps="+" if t["pnl"] >= 0 else "−",
            pa=abs(t["pnl"]), pct=t["pct"], r=t["reason"])
        for t in closed) or '<tr><td class="mut" colspan="8">no closed trades yet</td></tr>'
    wins = [t for t in st["closed"] if t["pnl"] > 0]
    stats = '<div class="note">win rate {}% &middot; {} wins / {} losses</div>'.format(
        round(100 * len(wins) / len(st["closed"])), len(wins),
        len(st["closed"]) - len(wins)) if st["closed"] else ""

    arows = "".join(
        '<tr><td class="mono mut">{d}</td><td class="mono {c}"><b>{side}</b></td>'
        '<td class="mono"><b>{t}</b></td><td class="mono r">{sh}</td>'
        '<td class="mono r">${p:.2f}</td><td class="mono r">${v:.2f}</td></tr>'.format(
            d=_short(ts), c="gain" if side == "buy" else "loss", side=side.upper(),
            t=t, sh=sh, p=price, v=value)
        for ts, side, t, sh, price, value, *_ in reversed(st["trades_asc"][-30:])) or \
        '<tr><td class="mut">none yet</td></tr>'

    drows = "".join('<tr><td class="mono mut" style="white-space:nowrap">{d}</td>'
                    '<td><span class="chip">{k}</span></td>'
                    '<td class="note" style="font-size:11.5px">{t}</td></tr>'.format(
                        d=_short(ts), k=kind, t=detail[:200])
                    for ts, kind, detail in st["decisions"])

    body = panel("🏆 Halls of Fame &amp; Shame", "ledger " + st["now"], _hall(st["closed"]))
    body += '<div class="grid2">'
    body += panel("P/L by window", "ledger " + st["now"], _period_stats(st["closed"]))
    body += panel("Weekly P/L", "ledger " + st["now"], _weekly_bars(st["closed"]))
    body += "</div>"
    body += panel("Equity curve", "snapshot " + st["now"],
                  _equity_svg(st["curve"], st["deposited"]))
    body += panel("Closed trades", "ledger " + st["now"],
                  '<table><tr><th>Closed</th><th>Ticker</th><th class="r">Qty</th>'
                  '<th class="r">In</th><th class="r">Out</th><th class="r">P/L $</th>'
                  '<th class="r">P/L %</th><th>Exit</th></tr>{}</table>{}'.format(crows, stats))
    body += panel("All activity (last 30)", "ledger " + st["now"],
                  '<table><tr><th>When</th><th>Side</th><th>Ticker</th><th class="r">Qty</th>'
                  '<th class="r">Price</th><th class="r">Value</th></tr>{}</table>'.format(arows))
    body += panel("Decision log (last 40) — every choice, including inaction",
                  "ledger " + st["now"], "<table>{}</table>".format(drows))
    return body


# ---------------- entry ----------------

def generate():
    st = _fetch_state()
    cfg, research, gen = st["cfg"], st["research"], st["now"]
    # mood drives the ambient effect: net P/L vs deposits, with a small deadband
    net = st["equity"] - st["deposited"] if st["deposited"] else 0.0
    pct = (net / st["deposited"] * 100) if st["deposited"] else 0.0
    mood = "up" if pct > 0.5 else ("down" if pct < -0.5 else "flat")
    pages = {
        "index.html": _page("index.html", _overview(st), cfg, research, gen, mood),
        "radar.html": _page("radar.html", _radar(st), cfg, research, gen, mood),
        "history.html": _page("history.html", _history(st), cfg, research, gen, mood),
    }
    publish_dir = os.path.join(ROOT, "publish")
    for name, html in pages.items():
        with open(os.path.join(ROOT, name if name != "index.html" else "dashboard.html"), "w") as f:
            f.write(html)
        if os.path.isdir(publish_dir):
            with open(os.path.join(publish_dir, name), "w") as f:
                f.write(html)
    return os.path.join(ROOT, "dashboard.html"), pages["index.html"]


if __name__ == "__main__":
    print("wrote", generate()[0])
